### ISSUE TITLE
CSV Reader Error

### ISSUE THREAD

**Issue by adityakamble49** [vivekpanchal/BabyApp#3]
Your csv file has contents like this
```
22,Boy,"Sri shandarachary, founder of adwaitha philosophy",Aadhishankar,Bengali
```
As it has commas inside token that's why you are getting wrong results, getting description of name instead of name itself

It has commas inside single token but it is surrounded by ""

You can do this manually or I would suggest to use OpenCSV Library to do that
Refer this tutorial to use open csv - [Here](https://www.journaldev.com/12014/opencsv-csvreader-csvwriter-example)

**Comment by vivekpanchal** [comment]
thanks will be working on that

**Comment by vivekpanchal** [comment]
CSV ERROR Fixed ..!!!!!
